# Used by calling 'site.*'
title: simonfinney.github.io
url: localhost:3000

# Jekyll input and output folders
source: src
destination: serve

# Called using 'site.author.*'
author:
  twitter: SimonJFinney
  github: simonfinney

# Google Analytics
google_analytics: UA-XXXXX-X

# _config.build.yml overwrites these when `gulp build` is run
# Enables drafts
future: true
show_drafts: true

# Disables the more accurate related posts for faster generating of the site
lsi: false

# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure options
permalink: pretty

# Markdown library
markdown: redcarpet

# Markdown library options
redcarpet:
  extensions: [
  'no_intra_emphasis',
  'tables',
  'fenced_code_blocks',
  'autolink',
  'smart',
  'strikethrough',
  'superscript',
  'underline',
  'footnotes'
  ]
